name: Code Quality

on:
  - push

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm vitest --run --coverage

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install
      - name: ESLint
        run: pnpm run lint
      - name: Typescript
        if: always()
        run: pnpm tsc --noEmit -p tsconfig.json
      - name: Prettier
        if: always()
        run: pnpm prettier --check src
